# Generated by Django 5.2.6 on 2025-09-27 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_room', models.CharField(max_length=10, verbose_name='Номер аудитории')),
                ('floor', models.IntegerField(verbose_name='Этаж')),
                ('status', models.CharField(choices=[('free', 'Свободна'), ('busy', 'Занята')], default='free', max_length=10, verbose_name='Статус')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Телефон')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='teachers/', verbose_name='Фотография')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_group', models.CharField(max_length=100, verbose_name='Название группы')),
                ('students_count', models.PositiveIntegerField(default=0, verbose_name='Количество студентов')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.teacher', verbose_name='Куратор')),
            ],
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_dis', models.CharField(max_length=100, verbose_name='Название дисциплины')),
                ('duration_hours', models.PositiveIntegerField(verbose_name='Количество часов обучения')),
                ('exam', models.CharField(max_length=100, verbose_name='Форма контроля')),
                ('status', models.CharField(choices=[('planned', 'Запланировано'), ('ongoing', 'Идет'), ('finished', 'Завершено')], default='planned', max_length=10, verbose_name='Статус')),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.classroom', verbose_name='Аудитория')),
                ('teachers', models.ManyToManyField(related_name='disciplines', to='schedule.teacher', verbose_name='Преподаватели')),
            ],
        ),
    ]
