# Generated by Django 5.2.6 on 2025-09-27 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='duration_hours',
            field=models.PositiveIntegerField(blank=True, default=50, null=True, verbose_name='Количество часов обучения'),
        ),
    ]
