# Generated by Django 5.2.6 on 2025-09-29 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_alter_discipline_duration_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='gmail',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Gmail'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='number_room',
            field=models.CharField(max_length=20, verbose_name='Номер аудитории'),
        ),
    ]
