# Generated by Django 5.2.6 on 2025-09-29 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_teacher_gmail_teacher_position_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discipline',
            name='teachers',
        ),
        migrations.AddField(
            model_name='teacher',
            name='disciplines',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='schedule.discipline', verbose_name='Дисциплины'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='floor',
            field=models.PositiveIntegerField(verbose_name='Этаж'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='status',
            field=models.CharField(choices=[('free', 'Доступна'), ('busy', 'Занята'), ('repair', 'На ремонте')], default='free', max_length=10, verbose_name='Статус'),
        ),
    ]
