# Generated by Django 5.2.6 on 2025-09-29 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_remove_discipline_teachers_teacher_disciplines_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='disciplines',
        ),
        migrations.AddField(
            model_name='discipline',
            name='teachers',
            field=models.ManyToManyField(related_name='disciplines', to='schedule.teacher', verbose_name='Преподаватели'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='number_room',
            field=models.CharField(max_length=10, verbose_name='Номер аудитории'),
        ),
    ]
