# Generated by Django 5.2.6 on 2025-10-06 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_remove_teacher_disciplines_discipline_teachers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discipline',
            name='exam',
        ),
        migrations.AddField(
            model_name='discipline',
            name='control_type',
            field=models.CharField(choices=[('exam', 'Экзамен'), ('test', 'Зачет'), ('coursework', 'Курсовая работа')], default='exam', max_length=20, verbose_name='Форма контроля'),
        ),
        migrations.AddField(
            model_name='group',
            name='shift',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Первая смена (дневная)'), (2, 'Вторая смена (послеобеденная)')], default=1, verbose_name='Смена'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='status',
            field=models.CharField(choices=[('active', 'Активный'), ('inactive', 'Неактивный')], default='active', max_length=10, verbose_name='Статус'),
        ),
    ]
