# Generated by Django 5.2.6 on 2025-10-09 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_remove_discipline_exam_discipline_control_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='name_short',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Сокращение'),
        ),
    ]
