# Generated by Django 5.2.6 on 2025-10-09 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_discipline_name_short'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='course',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 курс'), (2, '2 курс'), (3, '3 курс'), (4, '4 курс')], default=1, verbose_name='Курс'),
        ),
    ]
