# Generated by Django 5.2.6 on 2025-10-16 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_group_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.PositiveSmallIntegerField(choices=[(1, 'Первая смена'), (2, 'Вторая смена')], default=1, verbose_name='Смена')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница')], verbose_name='День недели')),
                ('week_type', models.CharField(choices=[('numerator', 'Числитель'), ('denominator', 'Знаменатель')], default='numerator', max_length=20, verbose_name='Тип недели')),
                ('lesson_number', models.PositiveSmallIntegerField(choices=[(1, '1 пара'), (2, '2 пара'), (3, '3 пара'), (4, '4 пара')], verbose_name='Номер пары')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Начало')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Конец')),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.classroom', verbose_name='Аудитория')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.discipline', verbose_name='Дисциплина')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.group', verbose_name='Группа')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.teacher', verbose_name='Преподаватель')),
            ],
        ),
    ]
