# Generated by Django 5.2.6 on 2025-11-18 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0009_classschedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discipline',
            name='classroom',
        ),
        migrations.AlterField(
            model_name='group',
            name='shift',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Первая смена'), (2, 'Вторая смена')], default=1, verbose_name='Смена'),
        ),
        migrations.AddField(
            model_name='discipline',
            name='classroom',
            field=models.ManyToManyField(blank=True, related_name='disciplines', to='schedule.classroom', verbose_name='Аудитории'),
        ),
    ]
